# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

ads: 'ezoic'

# Jekyll specific
future                   : false

# Site Settings
locale                   : "da"
title                    : "Fodboldens Legestue"
title_separator          : false # "-"
subtitle                 : "Fodboldtricks, fodboldrytmer, fodboldlege og fodboldøvelser"
logo                     : "/assets/images/logo-40x40.png"
name                     : "Fodboldens Legestue"
description              : "Fodboldtricks, fodboldrytmer, fodboldlege og fodboldøvelser. Søger du inspiration til tricks, lege og øvelser til fodbold?"
url                      : "https://www.legestue.net" # "https://www.legestue.net" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "lsolesen/legestue-net-jekyll" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
comments:
  provider               : disqus # "disqus" # "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : "legestue"
staticman:
  branch                 : "master"
atom_feed:
  path                   : # blank (default) uses feed.xml

signup:
  enabled: true
  provider: mailchimp # false
  url: https://legestue.us1.list-manage.com/subscribe/post?u=0e768d72de9dc35f20ab9159e&amp;id=54536f96cf&amp;f_id=00ca78e2f0
  recaptcha: b_0e768d72de9dc35f20ab9159e_54536f96cf

# reCaptcha
# Register your domain at https://www.google.com/recaptcha/ and choose reCAPTCHA V2
# reCaptcha:
#  enabled: true
#  siteKey: "6LdCtVoUAAAAADcxG1WekIUuEuJy3YPoQ8DtbzK8"
#  # Encrypt reCaptcha secret key using Staticman /encrypt endpoint
#  # For more information, https://staticman.net/docs/encryption
#  secret: "B6TmweBhBmEXsUUZKFEXOuFbAOHGBluvOCpsyTzAR+jjB5IkDNXzQo2NmMt8alWLWHh1HentKbOWAOx7HCl7AH3qgSeGWIvaTV99lKC8IakuyWGd2ZJR+eGxqN5RbmiNA1e4NXT4Z3DEMzq89iM/1VFkjSOY+LqAtWkdpJQTIGQ="


# SEO Related
google_site_verification : # XrBJvDdRdqOQQEbceemaTB2Ufx4g2Ir0wTN9dKIjc9M
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification : 97bdc4a9e0c1aaff


# Social Sharing
twitter:
  username               : "legestue"
facebook:
  username               : "legestue"
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Organization" # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/legestue"
    - "https://facebook.com/legestue"
    - "https://www.pinterest.dk/legestue/"
    - "https://www.youtube.com/user/fodboldenslegestue"


# Site search
search: true


# Analytics
analytics:
  provider               : false # "google-gtag" # false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-793671-2"


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/legestue"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/legestue"
    - label: "Pinterest"
      icon: "fab fa-fw fa-pinterest"
      webslides: "fa-pinterest"
      url: "https://www.pinterest.dk/legestue/"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      webslides: "fa-youtube"
      url: "https://www.youtube.com/user/fodboldenslegestue"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lsolesen/legestue-net-jekyll"


# Site Author
author:
  name: "Fodboldens Legestue"
  bio: "Fodboldens Legestues ambition er at gøre fodbold sjovere at spille og kigge på. Det startede med et hæfte med tricks, som vandt Kinnarpsprisen på DBUs Fodboldskole 1996, men er nu blevet et koncept, som er en måde at tænke fodbold på."
  avatar: "/assets/images/authors/kick.png"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:lars@legestue.net"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "http://www.facebook.com/legestue"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "http://www.youtube.com/fodboldenslegestue"
    - label: "Pinterest"
      icon: "fab fa-fw fa-pinterest"
      webslides: "fa-pinterest"
      url: "https://www.pinterest.dk/legestue/"
    - label: "Støt sitet"
      icon: "fas fa-fw fa-mug-hot"
      url: "https://www.buymeacoffee.com/lsolesen"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/legestue"
#    - label: "Pinterest"
#      icon: "fab fa-fw fa-pinterest-square"
#      url: "http://www.pinterest.com/legestue"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/lsolesen/legestue-net-jekyll.git"
#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      url: "https://larsolesen.dk"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Build settings
github: [metadata]


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:title/
paginate: 500 # amount of posts to show
paginate_path: /page/:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-gzip
  - jekyll-brotli


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-sitemap


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Collections
collections:
  soccerrythms:
    output: true
    permalink: /fodboldrytmer/:path/
  tricks:
    output: true
    permalink: /tricks/:path/
  redirects:
    output: true
    permalink: /go/:path/
  paid:
    output: true
    permalink: /tak/:path/
  giveaway:
    output: true
    permalink: /giveaway/:path/

# Defaults
defaults:
  - scope:
      path: "page"
    values:
      sitemap: false
  - scope:
      path: "assets/pdf/*.pdf"
    values:
      sitemap: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      author: lsolesen
      header:
        teaser: https://images.unsplash.com/photo-1490108474814-221f6198acc5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjIxMTIzfQ&auto=format&fit=crop&w=400&q=80
      sidebar:
        title: "Populære sider"
        nav: blog
# _soccerrythms
  - scope:
      path: ""
      type: soccerrythms
    values:
      layout: activity
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
# _tricks
  - scope:
      path: ""
      type: tricks
    values:
      layout: activity
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
      author: lsolesen
      category:
        - Fodboldtricks
# _redirects
  - scope:
      path: ""
      type: redirects
    values:
      layout: redirect
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sitemap: false
      disallow: true
      search: false
# _paid
  - scope:
      path: ""
      type: paid
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      disallow: true ## Used for noindex nofollow
      search: false
      sitemap: false
# _giveaway
  - scope:
      path: ""
      type: giveaway
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      disallow: true ## Used for noindex nofollow
      search: false
      sitemap: false
