name: legestue

backend:
  name: github
  repo: lsolesen/legestue-net-jekyll
  branch: master # Branch to update (optional; defaults to master)
  api_root: https://api.github.com
  site_domain: legestue.netlify.app
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: netlify-cms/
  open_authoring: true

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

site_url: https://www.legestue.net
display_url: https://www.legestue.net
logo_url: https://www.legestue.net/android-chrome-192x192.png

show_preview_links: false

editor:
  preview: false

publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "SEO Description", name: "description", widget: "text", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - label: Header
        name: header
        widget: object
        collapsed: true
        required: false
        fields:
          - {label: "Overlay Image", name: "overlay_image", widget: "string", required: false}
          - {label: "Teaser Image", name: "teaser", widget: "string", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
          - label: Actions
            name: actions
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
      - {label: "Category", name: "categories", widget: "list", allow_add: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Feature row
        name: feature_row
        widget: list
        collapsed: true
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Image", name: "image_path", widget: "string", required: false}
          - {label: "Alt", name: "alt", widget: "string", required: false}
          - {label: "Exerpt", name: "excerpt", widget: "text", required: false}
          - {label: "Url", name: "url", widget: "string", required: false}
          - {label: "Btn label", name: "btn_label", widget: "string", required: false}
          - {label: "Btn class", name: "btn_class", widget: "select", options: ["", "btn--success", "btn--warning", "btn--danger", "btn--info"], default: "", required: false}
      - label: Gallery
        name: gallery
        widget: list
        collapsed: true
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Alt", name: "alt", widget: "string"}
          - {label: "Image", name: "image_path", widget: "string"}
          - {label: "Url", name: "url", widget: "string"}
      - {label: "Last modified at", name: "last_modified_at", widget: "datetime", format: "YYYY-MM-DDThh:mm:ssZ", dateFormat: "dd-MM-YYYY", timeFormat: "HH:mm", required: false}
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Sider" # Used in the UI
    folder: "_pages/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "SEO Description", name: "description", widget: "text", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - label: Header
        name: header
        widget: object
        collapsed: true
        required: false
        fields:
          - {label: "Overlay Image", name: "overlay_image", widget: "string"}
          - {label: "Teaser Image", name: "teaser", widget: "string"}
          - {label: "Caption", name: "caption", widget: "string"}
          - label: Actions
            name: actions
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
      - {label: "Category", name: "category", widget: "list", allow_add: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Feature row
        name: feature_row
        widget: list
        collapsed: true
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Image", name: "image_path", widget: "string", required: false}
          - {label: "Alt", name: "alt", widget: "string", required: false}
          - {label: "Exerpt", name: "excerpt", widget: "text", required: false}
          - {label: "Url", name: "url", widget: "string", required: false}
          - {label: "Btn label", name: "btn_label", widget: "string", required: false}
          - {label: "Btn class", name: "btn_class", widget: "select", options: ["", "btn--success", "btn--warning", "btn--danger", "btn--info"], default: "", required: false}
      - label: Gallery
        name: gallery
        widget: list
        collapsed: true
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Alt", name: "alt", widget: "string"}
          - {label: "Image", name: "image_path", widget: "string"}
          - {label: "Url", name: "url", widget: "string"}
      - {label: "Last modified at", name: "last_modified_at", widget: "datetime", format: "YYYY-MM-DDThh:mm:ssZ", dateFormat: "dd-MM-YYYY", timeFormat: "HH:mm", required: false}
  - name: "tricks" # Used in routes, e.g., /admin/collections/blog
    label: "Tricks" # Used in the UI
    folder: "_tricks/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Difficulty", name: "difficulty", widget: "number", value_type: "int", min: 0, max: 6, step: 1, required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text",  required: false}
      - {label: "Instructions", name: "instructions", widget: "text",  required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Category", name: "categories", widget: "list", allow_add: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Header
        name: header
        widget: object
        collapsed: true
        required: false
        fields:
          - {label: "Overlay Image", name: "overlay_image", widget: "string"}
          - {label: "Teaser Image", name: "teaser", widget: "string"}
          - {label: "Caption", name: "caption", widget: "string"}
          - label: Actions
            name: actions
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
      - label: Gallery
        name: gallery
        widget: list
        collapsed: true
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image_path", widget: "string"}
          - {label: "Url", name: "url", widget: "string"}
      - {label: "Last modified at", name: "last_modified_at", widget: "datetime", format: "YYYY-MM-DDThh:mm:ssZ", dateFormat: "dd-MM-YYYY", timeFormat: "HH:mm", required: false}
  - name: "soccerrythms" # Used in routes, e.g., /admin/collections/blog
    label: "Fodboldrytmer" # Used in the UI
    folder: "_soccerrythms/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - label: Video
        name: video
        widget: object
        collapsed: true
        required: false
        fields:
          - {label: "Provider", name: "provider", widget: "string"}
          - {label: "Id", name: "id", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text",  required: false, collapsed: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "drafts" # Used in routes, e.g., /admin/collections/blog
    label: "Kladder" # Used in the UI
    folder: "_drafts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "SEO Description", name: "description", widget: "text", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - label: Header
        name: header
        widget: object
        collapsed: true
        required: false
        fields:
          - {label: "Overlay Image", name: "overlay_image", widget: "string", required: false}
          - {label: "Teaser Image", name: "teaser", widget: "string", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
          - label: Actions
            name: actions
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
      - {label: "Category", name: "categories", widget: "list", allow_add: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Feature row
        name: feature_row
        widget: list
        collapsed: true
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Image", name: "image_path", widget: "string", required: false}
          - {label: "Alt", name: "alt", widget: "string", required: false}
          - {label: "Exerpt", name: "excerpt", widget: "text", required: false}
          - {label: "Url", name: "url", widget: "string", required: false}
          - {label: "Btn label", name: "btn_label", widget: "string", required: false}
          - {label: "Btn class", name: "btn_class", widget: "select", options: ["", "btn--success", "btn--warning", "btn--danger", "btn--info"], default: "", required: false}
      - label: Gallery
        name: gallery
        widget: list
        collapsed: true
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Alt", name: "alt", widget: "string"}
          - {label: "Image", name: "image_path", widget: "string"}
          - {label: "Url", name: "url", widget: "string"}
      - {label: "Last modified at", name: "last_modified_at", widget: "datetime", format: "YYYY-MM-DDThh:mm:ssZ", dateFormat: "dd-MM-YYYY", timeFormat: "HH:mm", required: false}
  - label: "Site options"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Forsiden"
        name: "index"
        file: "index.html"
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "select", options: ["splash"], default: "splash"}
          - label: Header
            name: header
            widget: object
            collapsed: true
            required: false
            fields:
              - {label: "Image", name: "image", widget: "string", required: false}
              - {label: "Overlay Image", name: "overlay_image", widget: "string", required: false}
              - {label: "Teaser Image", name: "teaser", widget: "string", required: false}
              - {label: "Caption", name: "caption", widget: "string", required: false}
              - label: Actions
                name: actions
                widget: list
                collapsed: true
                required: false
                fields:
                  - {label: "Label", name: "label", widget: "string", required: false}
                  - {label: "Url", name: "url", widget: "string", required: false}
              - label: Video
                name: video
                widget: object
                collapsed: true
                required: false
                fields:
                  - {label: "Provider", name: "provider", widget: "select", options: ["youtube", "google-drive"], default: "", required: false}
                  - {label: "ID", name: "id", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: Feature row
            name: feature_row
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Image", name: "image_path", widget: "string", required: false}
              - {label: "Alt", name: "alt", widget: "string", required: false}
              - {label: "Exerpt", name: "excerpt", widget: "text", required: false}
              - {label: "Url", name: "url", widget: "string", required: false}
              - {label: "Btn label", name: "btn_label", widget: "string", required: false}
              - {label: "Btn class", name: "btn_class", widget: "select", options: ["", "btn--success", "btn--warning", "btn--danger", "btn--info"], default: "", required: false}
          - {label: "Last modified at", name: "last_modified_at", widget: "datetime", format: "YYYY-MM-DDThh:mm:ssZ", dateFormat: "dd-MM-YYYY", timeFormat: "HH:mm", required: false}
          - label: Gallery
            name: gallery
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Alt", name: "alt", widget: "string", required: false}
              - {label: "Image", name: "image_path", widget: "string", required: false}
              - {label: "Url", name: "url", widget: "string", required: false}
      - label: "Navigation Menu"
        name: nav
        file: "_data/navigation.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: main
            widget: list
            fields:
              - {label: "Display Text", name: title, widget: string}
              - {label: URL, name: url, widget: string}
          - label: "Sidelinks"
            label_singular: "Sidelink"
            name: blog
            widget: list
            fields:
              - {label: "Display Text", name: title, widget: string}
              - {label: "URL", name: url, widget: string, required: false}
              - label: "Links"
                name: children
                widget: list
                fields:
                  - {label: "Display Text", name: title, widget: string}
                  - {label: "URL", name: url, widget: string, required: false}
